trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true

- script: |
    terraform --version
    terraform init
    terraform plan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'








