trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "No dependencies to install."
    displayName: 'Skip dependency installation'

  - script: |
      echo "Running application without checking for dependencies."
    displayName: 'Inform about no dependencies'

  - script: |
      python app.py  # Or use gunicorn if you want to run it that way
    displayName: 'Run application'