trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pip show Flask Werkzeug
    displayName: 'Show installed versions'

  - script: |
      gunicorn --bind=0.0.0.0 --timeout 600 app:app
    displayName: 'Run application'