trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Installing dependencies."
      pip install -r requirements.txt || { echo "Dependency installation failed"; exit 1; }
    displayName: 'Install dependencies'

  - script: |
      echo "Running Flask application."
      python app.py || { echo "Flask application failed to start"; exit 1; }
    displayName: 'Run application'
