trigger:
  branches:
    include:
      - main  # Change if using a different branch

pool:
  vmImage: 'ubuntu-latest'

stages:
# --------------------- Stage 1: Build ---------------------
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
      displayName: 'Use Python 3.x'

    # Install dependencies in a virtual environment
    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    # Archive source files into a zip package
    - task: ArchiveFiles@2
      displayName: 'Archive source files'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

    # Publish the zip artifact
    - publish: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifact: app

# --------------------- Stage 2: Dev ---------------------
- stage: Dev
  dependsOn: Build
  jobs:
  - job: DeployToDev
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy to Dev Web App'
      inputs:
        azureSubscription: 'MyAzureConnection'  # Your service connection name
        appName: 'my-python-app'                  # Your Dev App Service name
        package: '$(Pipeline.Workspace)/app/app.zip'

# --------------------- Stage 3: Stage ---------------------
- stage: Stage
  dependsOn: Dev
  jobs:
  - job: DeployToStage
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy to Stage Web App'
      inputs:
        azureSubscription: 'MyAzureConnection'  # Your service connection name
        appName: 'my-python-app-staging'          # Your Staging App Service name
        package: '$(Pipeline.Workspace)/app/app.zip'
