trigger:
  branches:
    include:
      - main  # Trigger on push to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Using the latest Ubuntu image for the pipeline

steps:

  - task: Checkout@1
    displayName: 'Checkout code'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Use Python 3.x version
    displayName: 'Set up Python'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt  # Install dependencies from requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pytest --maxfail=1 --disable-warnings -q  # Running tests with pytest
    displayName: 'Run tests'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'MyAzureConnection'  # Azure service connection name
      appName: 'my-python-app'  # Name of your Azure Web App
      package: '.'  # Path to your package (this could be a zip file)
      runtimeStack: 'PYTHON|3.8'  # Python runtime stack version to use
    displayName: 'Deploy to Azure Web App'
