trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Installing dependencies."
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Running Flask application."
      gunicorn --bind=0.0.0.0 --timeout 600 app:app
    displayName: 'Run application'
