trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "No dependencies to install."
    displayName: 'Skip dependency installation'

  - script: |
      echo "Running Flask application directly."
    displayName: 'Inform about running application'

  - script: |
      python app.py  # Run the Flask application directly
    displayName: 'Run application'
