trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'free'  # ✅ Updated with your service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp up --name your-app-name --resource-group your-resource-group