trigger:
  branches:
    include:
      - main  # Trigger on push to main branch

pr:
  branches:
    include:
      - main  # Trigger on pull requests to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Installing dependencies."
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Activating virtual environment."
      source venv/bin/activate
      echo "Running Flask application."
      gunicorn --bind=0.0.0.0:8000 --timeout 600 app:app
    displayName: 'Run application'

