trigger:
  branches:
    include:
      - main  # or the branch you want to trigger on
  paths:
    include:
      - '**/*.tf'  # Only trigger when Terraform files are changed

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.4.0'  # Adjust as needed

steps:
- task: Checkout@2
  inputs:
    clean: true

- task: UseTerraform@0
  inputs:
    terraformVersion: $(terraformVersion)

- script: |
    terraform init
    terraform plan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'








