trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
      fetchDepth: 1
      condition: always()  # Ensures checkout runs even if a previous pipeline run failed

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - script: |
        python -m venv venv
        source venv/bin/activate  # For Linux/macOS
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install Dependencies'
      condition: succeeded()

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'  
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        artifactName: 'drop'

- stage: DeployToDev
  dependsOn: Build
  condition: succeeded()  # Only runs if Build stage succeeds
  jobs:
  - job: DeployDevJob
    steps:
    - task: DownloadBuildArtifacts@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    - script: ls -R $(Pipeline.Workspace)/drop
      displayName: "Check Artifacts Before Deployment"

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MyAzureConnection'
        appName: 'my-python-app'
        package: '$(Pipeline.Workspace)/drop/app.zip'

- stage: DeployToStaging
  dependsOn: DeployToDev
  condition: succeeded()
  jobs:
  - job: DeployStagingJob
    steps:
    - task: DownloadBuildArtifacts@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)'

    - script: ls -R $(Pipeline.Workspace)/drop
      displayName: "Check Artifacts Before Deployment"

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'MyAzureConnection'
        appName: 'my-python-app-staging'
        package: '$(Pipeline.Workspace)/drop/app.zip'


