trigger:
  branches:
    include:
      - main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'  # Choose the VM image you want to use

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'