trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "No dependencies to install."
    displayName: 'Skip dependency installation'

  - script: |
      python -m pip show Flask Werkzeug
    displayName: 'Show installed versions'

  - script: |
      gunicorn --bind=0.0.0.0 --timeout 600 app:app
    displayName: 'Run application'