trigger:
- main

variables:
- group: terraform_credential  # Variable group must have: CLIENT_ID, CLIENT_SECRET, SUBSCRIPTION_ID, TENANT_ID
- name: terraformVersion
  value: '1.5.5'

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Terraform
- task: UseTerraform@0
  inputs:
    terraformVersion: '$(terraformVersion)'

# Login to Azure using the service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'terraform-sc'  # Your service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Azure CLI login successful"

# Terraform Init
- script: |
    terraform init
  displayName: 'Terraform Init'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)

# Terraform Plan
- script: |
    terraform plan
  displayName: 'Terraform Plan'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)

# Terraform Apply
- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  env:
    CLIENT_ID: $(CLIENT_ID)
    CLIENT_SECRET: $(CLIENT_SECRET)
    SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
    TENANT_ID: $(TENANT_ID)






