trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Installing dependencies."
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Running Flask application directly."
    displayName: 'Inform about running application'

  - script: |
      python app.py  # Run the Flask application directly
    displayName: 'Run application'
