trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

# Terraform Init
- task: TerraformCLI@2
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)'
    backendType: 'azurerm'
    ensureBackend: false
    allowTelemetryCollection: false
    environmentServiceNameAzureRM: 'MyAzureConnection'

# Terraform Plan
- task: TerraformCLI@2
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceNameAzureRM: 'MyAzureConnection'

# Terraform Apply
- task: TerraformCLI@2
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceNameAzureRM: 'MyAzureConnection'
    commandOptions: '-auto-approve'











