trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@2
  inputs:
    clean: true

- task: UseTerraform@0
  inputs:
    terraformVersion: '1.4.0'

- script: |
    terraform init
    terraform plan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'








