
name: Azure Pipeline Trigger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Azure Pipeline
        uses: azure/pipelines@v1
        with:
          azure_devops_org: '0424282130'
          azure_devops_project: 'demo1'
          azure_devops_pat: ${{ secrets.AZURE_DEVOPS_PAT }}  # Add your PAT as a secret in GitHub
