
 name: Terraform CI/CD

on:
  push:
    paths:
      - '**/*.tf'  # Trigger only when .tf files are modified
  pull_request:
    paths:
      - '**/*.tf'  # Trigger when .tf files are modified in a PR

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0  # Adjust Terraform version if necessary

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_my_secret: ${{ secrets.AZURE_CREDENTIALS }}  # If you have secrets, replace with your secret variable